name: speech_to_text
description: A Flutter plugin that exposes device specific speech to text recognition capability.
version: 7.1.0-beta.3
homepage: https://github.com/csdcorp/speech_to_text
publish_to: none

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text_platform_interface:
    git: https://github.com/kumsumit/speech_to_text_platform_interface.git
  json_annotation: ^4.9.0
  clock: ^1.1.2
  lints: ^5.1.0
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.16.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  fake_async: ^1.3.2
  mockito: ^5.4.5
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.csdcorp.speech_to_text
        pluginClass: SpeechToTextPlugin
      ios:
        pluginClass: SpeechToTextPlugin
        sharedDarwinSource: true
      web:
        pluginClass: SpeechToTextPlugin
        fileName: speech_to_text_web.dart
      macos:
        pluginClass: SpeechToTextPlugin
        sharedDarwinSource: true
