name: speech_to_text_platform_interface
description: A common platform interface for the speech_to_text plugin.
homepage: https://github.com/csdcorp/speech_to_text/speech_to_text_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 2.3.0
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  plugin_platform_interface:
    git: https://github.com/kumsumit/plugin_platform_interface.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  flutter_lints: ^5.0.0
environment:
  sdk: ">=3.7.0 <4.0.0"
